name: bezier_chart
description: A beautiful bezier line chart widget for flutter that is highly interactive and configurable.
version: 1.0.17+1

homepage: https://aeyrium.com/products/mxtracker/
repository: https://github.com/aeyrium/bezier-chart

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
